CREATE TABLE IF NOT EXISTS users(
    username VARCHAR(50) PRIMARY KEY,
    password VARCHAR(60) NOT NULL,
    firstName VARCHAR(50),
    lastName VARCHAR(50),
    email VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS userProfile(
    username VARCHAR(50) PRIMARY KEY,
    bio VARCHAR(250),
    location VARCHAR(100),
    name VARCHAR(255) GENERATED ALWAYS AS (CONCAT(users.firstName, ' ', users.lastName)) STORED,
    FOREIGN KEY (username) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS products(
    imageSource VARCHAR(10000),
    title VARCHAR(1000),
    cost INT,
    description VARCHAR(10000),
    url VARCHAR(10000)
);

INSERT INTO products (imageSource, title, cost, description, url) VALUES 
('https://m.media-amazon.com/images/I/71Azp-504uL._AC_UL400_.jpg', 'Purina ONE Dry Dog Food Lamb and Rice Formula - 31.1 Lb. Bag', 46.53, 'Natural dog food with added vitamins, minerals, and nutrients has a Purina ONE SmartBlend ofhigh-quality ingredients, including quality carbohydrate sources, that helps support dog nutritional needs.', 'https://www.amazon.com/Purina-Smartblend-Natural-Formula-Adult/dp/B009IOCCD2/ref=sr_1_1_sspa?crid++++++++++++++++++++++++=2OJ905YMGZJRS&keywords=dog%2Bfood&qid=1681614881&rdc=1&sprefix=dog%2Bfood%2Caps%2C130&sr=8-1-spons&spLa++++++++++++++++++++++++=ZW5jcnlwdGVkUXVhbGlmaWVyPUFKRkEwUURLODJPRFUmZW5jcnlwdGVkSWQ9QTA1NjcyNzcyQ1lIM0NUSzIyN1NXJmVuY3J5cHRlZEFkSW++++++++++++++++++++++++Q9QTA2NzcyNDAxRkcxSjlVNk1SQ1U2JndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ++++++++++++++++++++++++&th=1'),
('https://m.media-amazon.com/images/I/81YzjUFh1BS._AC_SX679_.jpg', 'Purina Pro Plan High Protein Dog Food With Probiotics for Dogs, Shredded Blend Chicken & Rice Formula - 35 lb. Bag', 66.01, 'One (1) 35 lb. Bag - Purina Pro Plan High Protein Dog Food With Probiotics for Dogs, Shredded Blend Chicken & Rice Formula', 'https://www.amazon.com/Purina-Pro-Plan-Shredded-Chicken/dp/B001QCKS4O/ref=sr_1_1_sspa?crid=1XYFT9L6J6QA8&keywords=dog%2Bfood&qid=1682378300&rdc=1&sprefix=dog%2Bfood%2Caps%2C142&sr=8-1-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyRUVRTlgxWDZaOVQ2JmVuY3J5cHRlZElkPUEwNjEyNDA3M0FPMDVQTzkyWjhTWCZlbmNyeXB0ZWRBZElkPUEwMTA4Mjk0MzcwUlZTTkdHQzBBRyZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU&th=1'),
('https://m.media-amazon.com/images/I/81TdNfI0xjL._AC_SX679_.jpg', 'IAMS Adult High Protein Large Breed Dry Dog Food with Real Chicken, 30 lb. Bag', 46.98, 'Contains (1) 30 lb. bag of IAMS Adult Large Breed Dry Dog Food Chicken', 'https://www.amazon.com/Iams-Proactive-Health-Adult-Chicken/dp/B00BD74654/ref=sr_1_4_sspa?crid=1XYFT9L6J6QA8&keywords=dog%2Bfood&qid=1682378300&sprefix=dog%2Bfood%2Caps%2C142&sr=8-4-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyRUVRTlgxWDZaOVQ2JmVuY3J5cHRlZElkPUEwNjEyNDA3M0FPMDVQTzkyWjhTWCZlbmNyeXB0ZWRBZElkPUEwMzEwNzE5M1FCNU9ESlo2TEVHTCZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU&th=1'),
('https://m.media-amazon.com/images/I/610MpaqesNL._AC_SX679_.jpg', 'Niche Brands Dog Chew Toy for Aggressive chewers, Real Beef Flavored Non-Toxic Rubber Indestructible Dog Toys for Medium/Large Dogs, Dental Chews for Large Dog, Real Bone Shaped Gifts for Dogs', 13.49, '[Safer/Non-Toxic] Our dog toys are made of 100% food-grade natural rubber materials, so your dog even cat can lick or bite it arbitrarily without worrying about the negative effects of swallowing.', 'https://www.amazon.com/Niche-Brands-Aggressive-Non-Toxic-Indestructible/dp/B0BRWX863D/ref=sr_1_2_sspa?crid=36V6MWKQ4798C&keywords=dog+toys&qid=1682964361&sprefix=dog+fto%2Caps%2C138&sr=8-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyWEZOM1Q3QzNWUEhXJmVuY3J5cHRlZElkPUEwODM0MjcyMVlHNTlKWkY3SUs4SSZlbmNyeXB0ZWRBZElkPUEwMTcxMjQwMkRQQTdBUlJZREZMRiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU='),
('https://m.media-amazon.com/images/I/71h0a0IMnAS._AC_SX679_.jpg', 'HGB Squeaky Dog Toys, Octopus No Stuffing Crinkle Plush Dog Chew Toys for Puppy Teething, Pet Training and Entertaining, Durable Interactive Dog Toys for Puppies, Small, Medium, and Large Dogs, 2 Pack', 15.99, '[2 Pack Octopus Dog Toys] These funny octopus large dog toys with bright colors and cute looks will attract your dogs interest and keep them happy. These dog toys for large dogs are soft and lightweight, great for tug and fetch, easy for pets to carry, toss and roll around with. Its a great gift for puppies, small, medium, and large dogs', 'https://www.amazon.com/HGB-Stuffing-Teething-Entertaining-Interactive/dp/B098BB1HGN/ref=sr_1_4_sspa?crid=36V6MWKQ4798C&keywords=dog%2Btoys&qid=1682977227&sprefix=dog%2Bfto%2Caps%2C138&sr=8-4-spons&smid=A3AOV1LJEN4EKE&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyMVNROVBTWElNNFBSJmVuY3J5cHRlZElkPUEwMDg1ODc5MUNJTEMwREVBVTc4WSZlbmNyeXB0ZWRBZElkPUEwNDc2MDQzMlVLQTVURlVCU085QiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU&th=1'),
('https://m.media-amazon.com/images/I/61oz4-uEi9L._AC_SX679_.jpg', 'Dog Toys for Aggressive Chewers,Interactive Dog Toys Tug of War, Mentally Stimulating Toys for Dogs, Puppy Teething Toys for Boredom, Dog Puzzle Treat Food Dispensing Ball Toys for Small Large Dogs', 16.99, 'HEALTHY CHEWING】Chewing is a natural behavior of dogs. We dont need to stop it, just guide it properly. ALLRIERs durable dog toy is made of TPR, nontoxic and bite resistant extremely , Ensure your dog can play and chew it safely, and easy to clean.', 'https://www.amazon.com/ALLRIER-Aggressive-Training-Teething-Dispensing/dp/B0814Y7FK8/ref=sr_1_14_sspa?crid=36V6MWKQ4798C&keywords=dog+toys&qid=1682977227&sprefix=dog+fto%2Caps%2C138&sr=8-14-spons&psc=1&smid=A2S7FE0OXGTBPE&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyMVNROVBTWElNNFBSJmVuY3J5cHRlZElkPUEwMDg1ODc5MUNJTEMwREVBVTc4WSZlbmNyeXB0ZWRBZElkPUEwNjcwMTI5MTZZRVFMSzFITDRLTSZ3aWRnZXROYW1lPXNwX210ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU='),
('https://m.media-amazon.com/images/I/714eqPn93OL._AC_SX679_.jpg', 'Dog Shampoo with Oatmeal and Aloe. Shea Butter for Smelly Dogs, Puppy Shampoo by Olivers Choice 14 oz', 13.95, 'Specifically designed to deodorize and leave your dog smelling amazing and their coat restored!', 'https://www.amazon.com/Shampoo-Oatmeal-Sensitive-Olivers-Choice/dp/B081TMYWZR/ref=sr_1_1_sspa?crid=26NBZPVEOIF8W&keywords=dog+shampoo+and+conditioner&qid=1682977827&sprefix=dog+shampoo%2Caps%2C201&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExT0NFVldBVTlWOVE5JmVuY3J5cHRlZElkPUEwNzYwMTgwNDFTVUhJUUhQMlg5JmVuY3J5cHRlZEFkSWQ9QTA2NTAwNzczMDZRRjZYRlVFS0YzJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=='),
('https://m.media-amazon.com/images/I/51QB1mxgJEL._AC_SX679_.jpg', 'Earthbath Oatmeal & Aloe Shampoo & Conditioner Pet Grooming Set - Itchy, Dry Skin Relief, Made in USA - Vanilla & Almond, 16 oz', 25.95, 'HELPS RELIEVE ITCHING & DRY SKIN: This set includes one 16 oz shampoo and one 16 oz conditioner. Specially formulated for pets with dry, itchy, sensitive skin. Colloidal oatmeal and organic aloe vera help combat skin irritation, promote healing, and re-moisturize sensitive, dry skin.', 'https://www.amazon.com/Earthbath-Vanilla-Almond-Grooming-Bundle/dp/B0733Q6FZS/ref=sr_1_7?crid=26NBZPVEOIF8W&keywords=dog+shampoo+and+conditioner&qid=1682977914&sprefix=dog+shampoo%2Caps%2C201&sr=8-7'),
('https://m.media-amazon.com/images/I/71mntXlSfZL._AC_SX679_.jpg', 'We Love Doodles - Dog Shampoo, Conditioner, and Detangler - Best Shampoo for Goldendoodles and Doodles - Dog Shampoo for Puppies - Grooming, Organic Ingredients, Best Smelling, Made in USA (Lavender)', 15.99, '4-in-1 Dog Shampoo: Effectively cleans, conditions, detangles, and moisturizes your dogs skin. Keep your dogs fur soft, clean, and less tangled with one easy solution.', 'https://www.amazon.com/We-Love-Doodles-Conditioner-Goldendoodles/dp/B09Q837KK1/ref=sr_1_10?crid=26NBZPVEOIF8W&keywords=dog%2Bshampoo%2Band%2Bconditioner&qid=1682977914&sprefix=dog%2Bshampoo%2Caps%2C201&sr=8-10&th=1');